### ISSUE TITLE
Pushover Script

### ISSUE THREAD

**Issue by juanortega0410** [CJPCNZ/CustomPush#12]
Hi, first of all, I wanted to thank you for your hard work on these custom scripts, 

Easy to follow and set up.

I use pushbullet but I am wondering if the script can be converted to Pushover? I think half the work is done already but I am having a difficult time with it.  Attached is my attempt at replicating your script. (Didn't let me upload .sh file) [Pushover.txt](https://github.com/CJPCNZ/CustomPush/files/4547384/Pushover.txt)

If you have a chance, do you mind taking a look at it and seeing if you can get this to work. If not, I understand will continue using Pushbullet. Their Info site is below:

https://pushover.net/api#messages

Thank you

**Comment by CJPCNZ** [comment]
Hi @juanortega0410, thank you. It has been a nice challenge to work on these scripts.

Your script is pretty close, I've reviewed the API documentation and I think this should work:

```
#!/bin/bash
apikey="" # Your Radarr API key 
radarr_address="http://localhost:7878" # Your Radarr address (including base_url) 
pushkey="" # Your PushOver API key
pushuser="" # Your PushOver User Key

# Grab movie information
radarr_description=$(curl -s $radarr_address/api/movie/$radarr_movie_id --header "X-Api-Key:$apikey" | jq .overview)

# Format content
pushtitle+="Downloading: "
pushtitle+=$radarr_movie_title 
pushtitle+=" ("
pushtitle+=$radarr_movie_year
pushtitle+=")"

pushmessage=$radarr_description

# Prepare push notification body
pushbody=$( jq -n \
    --arg token "$pushkey" \
    --arg user "$pushuser" \
    --arg title "$pushtitle" \
    --arg message "$pushmessage" \
    '{token: $pushkey, user: $pushuser, title: $title, message: $message}' )

# Send push notification   
curl --header 'Content-Type: application/json' --data-binary "$pushbody" --request POST https://api.pushover.net/1/messages.json
```

Give that a try and if it works, I'll write one up for Sonarr as well and publish them with credit to you.

Any errors, please let me know and post any logs you have (excluding your API key or personal information). You can post code by highlighting the text and  clicking the <> icon in the Github editor.

**Comment by juanortega0410** [comment]
Hey, thank you for getting back to me so quick. I tried your code and unfortunately it gave me a bunch errors on a terminal screen and immediately closed on me. I can't figure out how to get the terminal to not close after executing the command. See pic attached of the errors.

![jq error](https://user-images.githubusercontent.com/37947508/80609549-390fe000-8a06-11ea-90bb-96e0ef9f0d09.jpg)

I did notice some "inconsistencies" with your code that may or may not be part of the problem, after trying a few different versions of your code it kept giving me same/similar errors... For example, user doesn't have a space before the $, is that OK? Most common error seems to be that the values are being defined correctly in the top level. Also, it keeps telling me that my token is invalid but that's the same one that Radarr is using right now and it's working fine.  

`'{token: $pushkey, user:$pushuser, title: $title, message: $message}' )`

Hopefully it's just syntax, spacing, extra commas or something... 

Thanks again!

**Comment by CJPCNZ** [comment]
Those errors indicate the variables have not been defined (ensure you've entered your pushkey and pushuser at the top of the file). The spacing shouldn't break the script but I've corrected it now.

Also make sure you save the file as PushOver.sh and follow the normal instructions:

### Linux
Follow the below steps replacing the relevant folder/file names

0. Run chmod +x on the PushOver.sh scripts (or set them to be Executable in the properties)
1. In Sonarr/Radarr go to **Settings > Connect > +**
2. Choose **Custom Script**
3. Check **On Download** and **On Upgrade**
4. Path: `\home\user\Sonarr\PushOver.sh` *Use the location where you saved the relevant .sh script*
5. Arguments: *Leave blank*
6. Test/Save

**Comment by juanortega0410** [comment]
Chris,

Thanks for the response but I don't I'm doing anything wrong with my username / keys. Seems straight forward and similar to the pushbullet format.

Below are the errors I am receiving. I did some research on the "not defined at top level" errors and it seems it has something to do with the formatting or defining of the variables . Didn't made much sense to me unfortunately.

`

PushOver.sh | 100 121 0 121 0 0 408 0 --:--:-- --:--:-- --:--:-- 408 | 6:36pm
-- | -- | --
  | PushOver.sh | 100 121 0 121 0 0 410 0 --:--:-- --:--:-- --:--:-- 408 | 6:36pm
  | PushOver.sh | 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 | 6:36pm
  | PushOver.sh | Dload Upload Total Spent Left Speed | 6:36pm
  | PushOver.sh | % Total % Received % Xferd Average Speed Time Time Time Current | 6:36pm
  | PushOver.sh | jq: 2 compile errors | 6:36pm
  | PushOver.sh | {token: $pushkey, user: $pushuser, title: $title, message: $message} | 6:36pm
  | PushOver.sh | jq: error: pushuser/0 is not defined at <top-level>, line 1: | 6:36pm
  | PushOver.sh | {token: $pushkey, user: $pushuser, title: $title, message: $message} | 6:36pm
  | PushOver.sh | jq: error: pushkey/0 is not defined at <top-level>, line 1: | 6:36pm

`

![File_001](https://user-images.githubusercontent.com/37947508/80655879-c32f6700-8a4d-11ea-975d-f2581bdea3b0.png)

**Comment by CJPCNZ** [comment]
Sorry I completely screwed that up. Replace the push preparation with this code:

```
# Prepare push notification body
pushbody=$( jq -n \
    --arg token "$pushkey" \
    --arg user "$pushuser" \
    --arg title "$pushtitle" \
    --arg message "$pushmessage" \
    '{token: $token, user: $user, title: $title, message: $message}' )
```

I had put the variable names instead of the push arguments.

**Comment by juanortega0410** [comment]
Chris,

You got it now. :)

Here's the script 100% working:

#!/bin/bash
apikey="" # Your Radarr API key 
radarr_address="http://localhost:7878" # Your Radarr address (including base_url) 
pushkey="" # Your PushOver API key
pushuser="" # Your PushOver User Key

# Grab movie information
radarr_description=$(curl -s $radarr_address/api/movie/$radarr_movie_id --header "X-Api-Key:$apikey" | jq .overview)

# Format content
pushtitle+="Downloading: "
pushtitle+=$radarr_movie_title 
pushtitle+=" ("
pushtitle+=$radarr_movie_year
pushtitle+=")"

pushmessage=$radarr_description

pushbody=$( jq -n \
    --arg token "$pushkey" \
    --arg user "$pushuser" \
    --arg title "$pushtitle" \
    --arg message "$pushmessage" \
    '{token: $token, user: $user, title: $title, message: $message}' )

# Send push notification   
curl --header 'Content-Type: application/json' --data-binary "$pushbody" --request POST https://api.pushover.net/1/messages.json

**Comment by CJPCNZ** [comment]
Awesome! Thank you so much for your patience and for completing testing, it has been very helpful.

I’ll get this uploaded with credit soon!

**Comment by juanortega0410** [comment]
> Awesome! Thank you so much for your patience and for completing testing, it has been very helpful.
> 
> I’ll get this uploaded with credit soon!

No problem, thank you. I sent you the Sonarr script as well. Much appreacited!!
