### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by jun6lee** [CJPCNZ/CustomPush#14]
Any plans or if not, could you make this support Slack too?

**Comment by CJPCNZ** [comment]
Hey @jun6lee I'm very sorry for the late reply, I have been offline until now but am back and ready to code!

I've just had a quick look through the documentation for Slack and it appears to be straightforward to setup so I will give it a go and post an update for you, hopefully in the next few days.

**Comment by CJPCNZ** [comment]
Hi there @jun6lee!

I've just added a set of scripts for Slack. If you have some time, could you please test one of them and let me know if you run into any issues? They're mostly the same but I don't have a slack account or site setup to test with.

Thanks!  👍

**Comment by CJPCNZ** [comment]
@jun6lee have you had a chance to test the Slack integration?

Please let me know if there are any issues.
