### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by jaycedk** [CJPCNZ/CustomPush#2]
Is it possible to add dvd/blue-ray cover art, to the message ?

**Comment by CJPCNZ** [comment]
It should work if the push service supports it. I will try to add this over
the weekend.

**Comment by jaycedk** [comment]
Great :) will be happy to test.
And thanks for the fast response.

**Comment by CJPCNZ** [comment]
I've spent some time on this and have been unable to get it working in Windows due to Powershell not supporting multipart forms properly. The linux version is working but it's a 3 step process just to get the image. If you need the code I'm happy to supply it but unless I can get it working reliably cross-platform I probably won't include it in the repository.

**Comment by jaycedk** [comment]
Ok.
Thanks for the effort and your time spend.
It would have been an great feature.

**Comment by CJPCNZ** [comment]
Hi @jaycedk I just wanted to let you know this has been bugging me so I set aside time to work on this today and have finally got Radarr working with images in Powershell. Are you able to test the "Pushbullet-WithImage.ps1" I just uploaded if you get a chance?

**Comment by jaycedk** [comment]
Sure getting right on it :)

**Comment by jaycedk** [comment]
Ok, its not pushing to my radarr channel, its now only pushing to my self.
And the image is not showing, but that might be a setting on my phone, that i have missed.
Any thing I should enable ? in my settings ?

**Comment by CJPCNZ** [comment]
Sorry, I've updated it again as I had the wrong variable in the channel. Do you see cover art in your Radarr? If you navigate to the completed movie and view the URL for the cover art is it something like http://localhost:7878/MediaCover/620/poster.jpg

**Comment by CJPCNZ** [comment]
Also you can comment line 59 with a # in front of it so that it doesn't remove the poster.jpg file. Then check the directory where your script lives and make sure that the poster file exists.
If possible post some logs from Radarr after it runs the script.

**Comment by jaycedk** [comment]
ok now its back to the right channel :)
And i can see the poster via the link, just edited that to my url for the movie testing on.
I have commented the line 59, so that the script dos not delete the poster file.
I have given Everyone full permissions on the folder where the script lives.
But im not seeing the poster file.

**Comment by CJPCNZ** [comment]
So the poster file gets created? Can you ensure line 57 includes -UseBasicParsing and add it if it's not there?

**Comment by jaycedk** [comment]
The -UseBasicParsing was not in the line.
And no the poser file is not created.

**Comment by CJPCNZ** [comment]
I’ve further modified the file now. UseBasicParsing needs to be in all of
the Invoke Request lines. Please update your file as required.

**Comment by jaycedk** [comment]
Sorry, having internet problems :(

**Comment by jaycedk** [comment]
ok got back online :)
Damn cable company :(
Updated the script, still not seeing the image file being created.

**Comment by jaycedk** [comment]
For good measure, just tried another movie.
Got no image on that either.

**Comment by jaycedk** [comment]
Well got to go for now.
Will be back later :)

**Comment by jaycedk** [comment]
Just a update.
Radarr log shows this.
Exception calling "ReadAllBytes" with "1" argument(s): "File 'C:\Windows\system32\poster.jpg' Not found."

**Comment by CJPCNZ** [comment]
Thanks for all your help and testing that’s exactly what I needed and what
I suspected might be the case. I’ll be back home shortly and will update
the script for you. Fingers crossed this works!

**Comment by jaycedk** [comment]
Super, will test it when I get home :)

**Comment by CJPCNZ** [comment]
Awesome, thanks! I've pushed an update now to include a path fix that should work. I also fixed another missing "-UseBasicParsing" there. It's late now so I probably won't be back until tomorrow.

**Comment by jaycedk** [comment]
Hi just tested the script again, here is the Radarr logs.


  | Time
-- | --
  | powershell.exe | + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand | 19:15
  | powershell.exe | eption | 19:15
  | powershell.exe | + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc | 19:15
  | powershell.exe | + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | 19:15
  | powershell.exe | + Invoke-WebRequest -Method POST -Uri "https://api.pushbullet.com/v2/pu ... | 19:15
  | powershell.exe | At C:\Convert\PushBullet-WithImage.ps1:78 char:1 | 19:15
  | powershell.exe | valid value.","param":"file_url","cat":"\u003e:3"},"error_code":"invalid_param"} | 19:15
  | powershell.exe | Invoke-WebRequest : {"error":{"code":"invalid_param","type":"invalid_request","message":"The param 'file_url' has an in | 19:15
  | powershell.exe | + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand | 19:15
  | powershell.exe | eption | 19:15
  | powershell.exe | + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc | 19:15
  | powershell.exe | + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | 19:15
  | powershell.exe | + Invoke-RestMethod -Uri $uploadImage.upload_url -Method Post -UseBasic ... | 19:15
  | powershell.exe | At C:\Convert\PushBullet-WithImage.ps1:57 char:1 | 19:15
  | powershell.exe | ze is 25MB.","param":"size","value":"0","max_upload_size":26214400,"cat":"\u003e:3"},"error_code":"invalid_request"} | 19:15
  | powershell.exe | Invoke-RestMethod : {"error":{"code":"invalid_request","type":"invalid_request","message":"File is too big.  Maximum si | 19:15
  | powershell.exe | + FullyQualifiedErrorId : ArgumentNullException | 19:14
  | powershell.exe | + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException | 19:14
  | powershell.exe | + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | 19:14
  | powershell.exe | + $fileEnc = [System.Text.Encoding]::GetEncoding('ISO-8859-1').GetStrin ... | 19:14
  | powershell.exe | At C:\Convert\PushBullet-WithImage.ps1:28 char:1 | 19:14
  | powershell.exe | Parameternavn: bytes" | 19:14
  | powershell.exe | Exception calling "GetString" with "1" argument(s): "En matrix m† ikke v‘re null. | 19:14
  | powershell.exe | + FullyQualifiedErrorId : FileNotFoundException | 19:14
  | powershell.exe | + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException | 19:14
  | powershell.exe | + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | 19:14
  | powershell.exe | + $fileBytes = [System.IO.File]::ReadAllBytes($FilePath); | 19:14
  | powershell.exe | At C:\Convert\PushBullet-WithImage.ps1:27 char:1 | 19:14
  | powershell.exe | Exception calling "ReadAllBytes" with "1" argument(s): "Filen 'C:\Convert\poster.jpg' blev ikke fundet." | 19:14
  | powershell.exe | + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand | 19:14
  | powershell.exe | eption | 19:14
  | powershell.exe | + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc | 19:14
  | powershell.exe | + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | 19:14
  | powershell.exe | + Invoke-WebRequest $radarr_image -UseBasicParsing -OutFile "$PSScriptR ... | 19:14
  | powershell.exe | At C:\Convert\PushBullet-WithImage.ps1:15 char:1 | 19:14
  | powershell.exe | Invoke-WebRequest : Fjernserveren returnerede en fejl: (401) Uautoriseret.

**Comment by jaycedk** [comment]
Hi just tried the new script.
Here is the Radarr logs.

`19-4-14 19:14:48.1|Error|powershell.exe|Invoke-WebRequest : Fjernserveren returnerede en fejl: (401) Uautoriseret.
19-4-14 19:14:48.1|Error|powershell.exe|At C:\Convert\PushBullet-WithImage.ps1:15 char:1
19-4-14 19:14:48.1|Error|powershell.exe|+ Invoke-WebRequest $radarr_image -UseBasicParsing -OutFile "$PSScriptR ...
19-4-14 19:14:48.1|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-14 19:14:48.1|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
19-4-14 19:14:48.1|Error|powershell.exe|   eption
19-4-14 19:14:48.1|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
19-4-14 19:14:59.8|Error|powershell.exe|Exception calling "ReadAllBytes" with "1" argument(s): "Filen 'C:\Convert\poster.jpg' blev ikke fundet."
19-4-14 19:14:59.8|Error|powershell.exe|At C:\Convert\PushBullet-WithImage.ps1:27 char:1
19-4-14 19:14:59.8|Error|powershell.exe|+ $fileBytes = [System.IO.File]::ReadAllBytes($FilePath);
19-4-14 19:14:59.8|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-14 19:14:59.8|Error|powershell.exe|    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
19-4-14 19:14:59.8|Error|powershell.exe|    + FullyQualifiedErrorId : FileNotFoundException
19-4-14 19:14:59.8|Error|powershell.exe|Exception calling "GetString" with "1" argument(s): "En matrix m† ikke v‘re null.
19-4-14 19:14:59.8|Error|powershell.exe|Parameternavn: bytes"
19-4-14 19:14:59.8|Error|powershell.exe|At C:\Convert\PushBullet-WithImage.ps1:28 char:1
19-4-14 19:14:59.9|Error|powershell.exe|+ $fileEnc = [System.Text.Encoding]::GetEncoding('ISO-8859-1').GetStrin ...
19-4-14 19:14:59.9|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-14 19:14:59.9|Error|powershell.exe|    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
19-4-14 19:14:59.9|Error|powershell.exe|    + FullyQualifiedErrorId : ArgumentNullException
19-4-14 19:15:00.3|Error|powershell.exe|Invoke-RestMethod : {"error":{"code":"invalid_request","type":"invalid_request","message":"File is too big.  Maximum si
19-4-14 19:15:00.3|Error|powershell.exe|ze is 25MB.","param":"size","value":"0","max_upload_size":26214400,"cat":"\u003e:3"},"error_code":"invalid_request"}
19-4-14 19:15:00.3|Error|powershell.exe|At C:\Convert\PushBullet-WithImage.ps1:57 char:1
19-4-14 19:15:00.3|Error|powershell.exe|+ Invoke-RestMethod -Uri $uploadImage.upload_url -Method Post -UseBasic ...
19-4-14 19:15:00.3|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-14 19:15:00.3|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc 
19-4-14 19:15:00.4|Error|powershell.exe|   eption
19-4-14 19:15:00.4|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
19-4-14 19:15:00.6|Error|powershell.exe|Invoke-WebRequest : {"error":{"code":"invalid_param","type":"invalid_request","message":"The param 'file_url' has an in
19-4-14 19:15:00.6|Error|powershell.exe|valid value.","param":"file_url","cat":"\u003e:3"},"error_code":"invalid_param"}
19-4-14 19:15:00.7|Error|powershell.exe|At C:\Convert\PushBullet-WithImage.ps1:78 char:1
19-4-14 19:15:00.7|Error|powershell.exe|+ Invoke-WebRequest -Method POST -Uri "https://api.pushbullet.com/v2/pu ...
19-4-14 19:15:00.7|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-14 19:15:00.7|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
19-4-14 19:15:00.7|Error|powershell.exe|   eption
19-4-14 19:15:00.8|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

**Comment by CJPCNZ** [comment]
The very first error is 401 Unauthorised. Could you please double check
your API key for Radarr and possibly try manually connecting to the API URL?

**Comment by jaycedk** [comment]
Hmm something is off.
I went back to the old scrips, to test the api key, and that works.
Copied the key to the new scrips, and that dident work.
Manually connecting to the API URL ? what dos that url look like.

**Comment by CJPCNZ** [comment]
Can you go to the poster.jpg file (http://localhost:7878/MediaCover/620/poster.jpg) on your Radarr server and see how big it is? One of the errors is that a file is too big (over 25mb).

To test the API use something like this (1 can be the movie ID):
http://localhost:7878/api/movie/1?apikey=YOURAPIKEY

Another test you could try is replacing 
"$PSScriptRoot\poster.jpg" with "C:\Convert\poster.jpg" throughout the script (line 15, 26 and 59)

**Comment by jaycedk** [comment]
Hi Im at work atm.
Will test this tonight :)

**Comment by jaycedk** [comment]
Hi again.
I can get my poster using http://localhost:xxxx/MediaCover/xxxx/poster.jpg
The image is only 489kb.

http://localhost:7878/api/movie/620?apikey=Mykey 
I get the xml file.

Tried replacing the "$PSScriptRoot\poster.jpg" with "C:\Convert\poster.jpg" at line 15, 26 and 59.
Still no luck.
And the errors look the same.

**Comment by CJPCNZ** [comment]
Have you got Powershell ISE? Try running this portion only (or enter your api details, copy and paste in Powershell directly):

```
# Define required variables
$radarr_movie_id = "620"
$radarr_movie_title = "TEST TITLE"
$radarr_moviefile_quality = "1080P"

$apikey="" # Your Radarr API key 
$radarr_address="http://localhost:7878" # Your Radarr address (including base_url) 

# Grab movie information
$radarr_movie=$(Invoke-WebRequest -URI $radarr_address/api/movie/$radarr_movie_id?apikey=$apikey -UseBasicParsing) | ConvertFrom-Json
$radarr_description = $radarr_movie | Select-Object -ExpandProperty overview
$radarr_image = $radarr_address + "/MediaCover/" + $radarr_movie_id + "/poster.jpg"
Invoke-WebRequest $radarr_image -UseBasicParsing -OutFile "C:\Convert\poster.jpg"
```

That should make the file appear at least.

**Comment by jaycedk** [comment]
I have basic authentication enabled.
Username and password.
Just tried and disable that and now, the script works.

But I really need to have the username and password enabled.

**Comment by CJPCNZ** [comment]
That explains the 401 error. I’m just heading home now to take a look. Your
old script should have a username and password somewhere for the basic
authentication. That will need to be added to the line querying the Radarr
api if you can find it. If not I will update the script for you tonight to
include username and password.

**Comment by jaycedk** [comment]
For some reason i have deletet the old script "dohh"
So if and when you get the time, I would love the updatet with username and password :)
And thanks for all your help.

**Comment by CJPCNZ** [comment]
No worries, it happens. :) 
Give the latest commit a try, just enter your username and password on 12 and 13. I think in some setups you can use username:password@localhost:7878 but I wasn't able to get that working in here. This method seemed to be the most reliable.

**Comment by jaycedk** [comment]
Just tried you updated script.
And running it manually with Powershell ISE.
I'm prompted to enter username and password.
Only after entering my creds, is the poster file created.

# Define required variables
$radarr_movie_id = "620"
$radarr_movie_title = "TEST TITLE"
$radarr_moviefile_quality = "1080P"

$apikey="" # Your Radarr API key 
$radarr_address="http://localhost:7878" # Your Radarr address (including base_url) 

# Change $null to "username" / "password" if you use basic authentication in Radarr
$user = "MyRadarrUser"
$pass = "MyRadarrPass"

if (($null -ne $user) -and ($null -ne $pass)){
# Create authentication value
$pair = "$($user):$($pass)"
$encodedCreds = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($pair))
$basicAuthValue = "Basic $encodedCreds"

# Grab movie information
$radarr_movie=$(curl -URI $radarr_address/api/movie/$radarr_movie_id -UseBasicParsing -Credential $basicAuthValue -Header @{"X-Api-Key" = $apikey}) | ConvertFrom-Json
$radarr_description = $radarr_movie | Select-Object -ExpandProperty overview
$radarr_image = $radarr_address + "/MediaCover/" + $radarr_movie_id + "/poster.jpg"
Invoke-WebRequest $radarr_image -UseBasicParsing -OutFile "c:\convert\poster.jpg" -Credential $basicAuthValue
} Else {
# Grab movie information
$radarr_movie=$(curl -URI $radarr_address/api/movie/$radarr_movie_id -UseBasicParsing -Header @{"X-Api-Key" = $apikey}) | ConvertFrom-Json
$radarr_description = $radarr_movie | Select-Object -ExpandProperty overview
$radarr_image = $radarr_address + "/MediaCover/" + $radarr_movie_id + "/poster.jpg"
Invoke-WebRequest $radarr_image -UseBasicParsing -OutFile "c:\convert\poster.jpg"
}

**Comment by CJPCNZ** [comment]
Well that's progress! :) Thank you for being so patient.
I have changed to header authentication which might work better. Specifically Line 22 and 25 have be replaced.

**Comment by jaycedk** [comment]
No problem :) Its also something I would like to see work :)
It works :) 👍 

So now we have it working 
1) Api only / no authentication
2) Basic ( Browser popup )
Then we just need the last, Forms ( Login page )

And here is the log from Radarr about that :P 
`19-4-17 18:18:57.9|Error|powershell.exe|Invoke-WebRequest : {"error":{"code":"invalid_access_token","type":"invalid_request","message":"Access token is missing
19-4-17 18:18:58.0|Error|powershell.exe| or invalid.","cat":"(=^???^)y="},"error_code":"invalid_access_token"}
19-4-17 18:18:58.0|Error|powershell.exe|At C:\convert\PushBullet-WithImage1.ps1:40 char:16
19-4-17 18:18:58.0|Error|powershell.exe|+ ... loadImage = Invoke-WebRequest -Method POST -Uri "https://api.pushbull ...
19-4-17 18:18:58.0|Error|powershell.exe|+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-17 18:18:58.0|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
19-4-17 18:18:58.0|Error|powershell.exe|   eption
19-4-17 18:18:58.0|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
19-4-17 18:18:58.0|Error|powershell.exe|Cannot index into a null array.
19-4-17 18:18:58.0|Error|powershell.exe|At C:\convert\PushBullet-WithImage1.ps1:41 char:1
19-4-17 18:18:58.0|Error|powershell.exe|+ $uploadData = $uploadImage.data[0]
19-4-17 18:18:58.1|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-17 18:18:58.2|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
19-4-17 18:18:58.3|Error|powershell.exe|    + FullyQualifiedErrorId : NullArray
19-4-17 18:18:58.4|Error|powershell.exe|Invoke-RestMethod : Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument tha
19-4-17 18:18:58.5|Error|powershell.exe|t is not null or empty, and then try the command again.
19-4-17 18:18:58.6|Error|powershell.exe|At C:\convert\PushBullet-WithImage1.ps1:74 char:24
19-4-17 18:18:58.7|Error|powershell.exe|+ Invoke-RestMethod -Uri $uploadImage.upload_url -Method Post -UseBasic ...
19-4-17 18:18:58.7|Error|powershell.exe|+                        ~~~~~~~~~~~~~~~~~~~~~~~
19-4-17 18:18:58.8|Error|powershell.exe|    + CategoryInfo          : InvalidData: (:) [Invoke-RestMethod], ParameterBindingValidationException
19-4-17 18:18:58.9|Error|powershell.exe|    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
19-4-17 18:18:59.0|Error|powershell.exe|Invoke-WebRequest : {"error":{"code":"invalid_access_token","type":"invalid_request","message":"Access token is missing
19-4-17 18:18:59.1|Error|powershell.exe| or invalid.","cat":"(=^???^)y="},"error_code":"invalid_access_token"}
19-4-17 18:18:59.2|Error|powershell.exe|At C:\convert\PushBullet-WithImage1.ps1:95 char:1
19-4-17 18:18:59.3|Error|powershell.exe|+ Invoke-WebRequest -Method POST -Uri "https://api.pushbullet.com/v2/pu ...
19-4-17 18:18:59.3|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-17 18:18:59.4|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
19-4-17 18:18:59.5|Error|powershell.exe|   eption
19-4-17 18:18:59.6|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

**Comment by CJPCNZ** [comment]
I have tested this against basic and forms authentication and the same code seems to work.
The error you're receiving now is from Pushbullet indicating you have an invalid or incorrect Pushbullet API key. The variable should be $pushkey on line 9 which is called on line 40 to start the upload process.

**Comment by jaycedk** [comment]
You are right, it is indeed working :)
Just tried it again, guess some fluck at Pushbullet end ;)

**Comment by CJPCNZ** [comment]
Awesome! That cat is etched into my memory from the countless issues I had getting it setup.
Is there anything else you need changed on this?

**Comment by jaycedk** [comment]
Not on this, but can we do the same with Sonarr :)

**Comment by jaycedk** [comment]
And Lidarr :P if you know that.

**Comment by CJPCNZ** [comment]
Happy to give Lidarr a try though I've never used it so may take a while. Please raise a new feature request for each system. Are you wanting the login part added or the image inside push notifications?

I've got to get this added to the bash scripts as well which I'll try to do this weekend.
