### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jaycedk** [CJPCNZ/CustomPush#4]
Can you make a script for Lidarr, like you have for Radarr and Sonarr.
With cover art and login.

**Comment by jaycedk** [comment]
If you don't know Lidarr, it is like Radarr and Sonarr, just for Music.

**Comment by CJPCNZ** [comment]
Unfortunately I'm flying by documentation on this but their API is similar to Radarr. Can you get me the covert art path for one of your albums? e.g. localhost:8686/MediaCover/id/poster.jpg ?

**Comment by CJPCNZ** [comment]
I've just uploaded a first sample. Give it a try and post any error logs.

**Comment by jaycedk** [comment]
localhost:8686/MediaCover/4/poster-500.jpg?lastWrite=634839885980000000
This is the picture link.

**Comment by jaycedk** [comment]
Log file for the first script
`19-4-21 09:09:15.8|Error|powershell.exe|Invoke-WebRequest : Fjernserveren returnerede en fejl: (404) Ikke fundet.
19-4-21 09:09:15.8|Error|powershell.exe|At C:\Convert\Lidarr.ps1:22 char:17
19-4-21 09:09:15.8|Error|powershell.exe|+ ... arr_album=$(Invoke-WebRequest  -URI $lidarr_address/api/album/$lidarr ...
19-4-21 09:09:15.8|Error|powershell.exe|+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-21 09:09:15.8|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
19-4-21 09:09:15.8|Error|powershell.exe|   eption
19-4-21 09:09:15.8|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
19-4-21 09:09:15.8|Warn|MediaCoverMapper|File C:\ProgramData\Lidarr\MediaCover\poster.jpg not found
19-4-21 09:09:15.8|Error|powershell.exe|Invoke-WebRequest : Fjernserveren returnerede en fejl: (404) Ikke fundet.
19-4-21 09:09:15.8|Error|powershell.exe|At C:\Convert\Lidarr.ps1:25 char:1
19-4-21 09:09:15.8|Error|powershell.exe|+ Invoke-WebRequest $lidarr_image -UseBasicParsing -OutFile "$PSScriptR ...
19-4-21 09:09:15.8|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-21 09:09:15.9|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
19-4-21 09:09:15.9|Error|powershell.exe|   eption
19-4-21 09:09:15.9|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
19-4-21 09:09:16.2|Error|powershell.exe|Exception calling "ReadAllBytes" with "1" argument(s): "Filen 'C:\Convert\poster.jpg' blev ikke fundet."
19-4-21 09:09:16.2|Error|powershell.exe|At C:\Convert\Lidarr.ps1:44 char:1
19-4-21 09:09:16.2|Error|powershell.exe|+ $fileBytes = [System.IO.File]::ReadAllBytes($FilePath);
19-4-21 09:09:16.3|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-21 09:09:16.3|Error|powershell.exe|    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
19-4-21 09:09:16.3|Error|powershell.exe|    + FullyQualifiedErrorId : FileNotFoundException
19-4-21 09:09:16.4|Error|powershell.exe|Exception calling "GetString" with "1" argument(s): "En matrix m† ikke v‘re null.
19-4-21 09:09:16.4|Error|powershell.exe|Parameternavn: bytes"
19-4-21 09:09:16.5|Error|powershell.exe|At C:\Convert\Lidarr.ps1:45 char:1
19-4-21 09:09:16.5|Error|powershell.exe|+ $fileEnc = [System.Text.Encoding]::GetEncoding('ISO-8859-1').GetStrin ...
19-4-21 09:09:16.5|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-21 09:09:16.6|Error|powershell.exe|    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
19-4-21 09:09:16.6|Error|powershell.exe|    + FullyQualifiedErrorId : ArgumentNullException
19-4-21 09:09:16.7|Error|powershell.exe|Invoke-RestMethod : {"error":{"code":"invalid_request","type":"invalid_request","message":"File is too big.  Maximum si
19-4-21 09:09:16.7|Error|powershell.exe|ze is 25MB.","param":"size","value":"0","max_upload_size":26214400,"cat":"\u003e:3"},"error_code":"invalid_request"}
19-4-21 09:09:16.8|Error|powershell.exe|At C:\Convert\Lidarr.ps1:74 char:1
19-4-21 09:09:16.8|Error|powershell.exe|+ Invoke-RestMethod -Uri $uploadImage.upload_url -Method Post -UseBasic ...
19-4-21 09:09:16.9|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-21 09:09:16.9|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc 
19-4-21 09:09:17.0|Error|powershell.exe|   eption
19-4-21 09:09:17.0|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
19-4-21 09:09:17.0|Error|powershell.exe|rm : Cannot find path 'C:\Convert\poster.jpg' because it does not exist.
19-4-21 09:09:17.1|Error|powershell.exe|At C:\Convert\Lidarr.ps1:76 char:1
19-4-21 09:09:17.2|Error|powershell.exe|+ rm "$PSScriptRoot\poster.jpg"
19-4-21 09:09:17.2|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-21 09:09:17.3|Error|powershell.exe|    + CategoryInfo          : ObjectNotFound: (C:\Convert\poster.jpg:String) [Remove-Item], ItemNotFoundException
19-4-21 09:09:17.3|Error|powershell.exe|    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
19-4-21 09:09:17.4|Error|powershell.exe|Invoke-WebRequest : {"error":{"code":"invalid_param","type":"invalid_request","message":"The param 'file_url' has an in
19-4-21 09:09:17.5|Error|powershell.exe|valid value.","param":"file_url","cat":"\u003e:3"},"error_code":"invalid_param"}
19-4-21 09:09:17.5|Error|powershell.exe|At C:\Convert\Lidarr.ps1:95 char:1
19-4-21 09:09:17.6|Error|powershell.exe|+ Invoke-WebRequest -Method POST -Uri "https://api.pushbullet.com/v2/pu ...
19-4-21 09:09:17.6|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-21 09:09:17.7|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
19-4-21 09:09:17.7|Error|powershell.exe|   eption
19-4-21 09:09:17.8|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

**Comment by jaycedk** [comment]
ok just an update.
The Album image is not downloaded locally https://assets.fanart.tv/fanart/music/cc2c9c3c-b7bc-4b8b-84d8-4fbd8779e493/albumcover/25-562e84cb674f9.jpg
So i guess we should use artist image.

**Comment by jaycedk** [comment]
ok just found this 
http://localhost:8686/api/v1/artist/8?apikey=9XXXXXXXXXXXXXXCFDDXXFXf
Guess we need to use /v1/artist/ or /v1/album

**Comment by CJPCNZ** [comment]
Sorry for the delay. I've amended the URLs now. I think I may need to change the paths further but hopefully now you should be able to test the completion of an album.

**Comment by jaycedk** [comment]
OK no problem, this is also a new request :)
I'm at a eater launch, but will test it later, if im sober enough ;)
Other wise tomorrow :P

**Comment by CJPCNZ** [comment]
Haha no stress at all, enjoy your lunch! :) I've got a lot of bash scripting to catch up on for now.

**Comment by jaycedk** [comment]
ok new error.
the script cant fint the picture :)
Its missing the ID nr. in the path.
`19-4-21 18:00:53.0|Warn|MediaCoverMapper|File C:\ProgramData\Lidarr\MediaCover\coverart.jpg not found
19-4-21 18:00:53.1|Error|powershell.exe|Invoke-WebRequest : Fjernserveren returnerede en fejl: (404) Ikke fundet.
19-4-21 18:00:53.1|Error|powershell.exe|At C:\Convert\Lidarr.ps1:24 char:1
19-4-21 18:00:53.2|Error|powershell.exe|+ Invoke-WebRequest $lidarr_image -UseBasicParsing -OutFile "$PSScriptR ...
19-4-21 18:00:53.2|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-21 18:00:53.2|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
19-4-21 18:00:53.2|Error|powershell.exe|   eption
19-4-21 18:00:53.2|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
19-4-21 18:00:53.5|Error|powershell.exe|Exception calling "ReadAllBytes" with "1" argument(s): "Filen 'C:\Convert\coverart.jpg' blev ikke fundet."
19-4-21 18:00:53.6|Error|powershell.exe|At C:\Convert\Lidarr.ps1:42 char:1
19-4-21 18:00:53.6|Error|powershell.exe|+ $fileBytes = [System.IO.File]::ReadAllBytes($FilePath);
19-4-21 18:00:53.6|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-21 18:00:53.6|Error|powershell.exe|    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
19-4-21 18:00:53.6|Error|powershell.exe|    + FullyQualifiedErrorId : FileNotFoundException
19-4-21 18:00:53.7|Error|powershell.exe|Exception calling "GetString" with "1" argument(s): "En matrix m† ikke v‘re null.
19-4-21 18:00:53.7|Error|powershell.exe|Parameternavn: bytes"
19-4-21 18:00:53.7|Error|powershell.exe|At C:\Convert\Lidarr.ps1:43 char:1
19-4-21 18:00:53.7|Error|powershell.exe|+ $fileEnc = [System.Text.Encoding]::GetEncoding('ISO-8859-1').GetStrin ...
19-4-21 18:00:53.7|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-21 18:00:53.8|Error|powershell.exe|    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
19-4-21 18:00:53.8|Error|powershell.exe|    + FullyQualifiedErrorId : ArgumentNullException
19-4-21 18:01:05.1|Error|powershell.exe|Invoke-RestMethod : {"error":{"code":"invalid_request","type":"invalid_request","message":"File is too big.  Maximum si
19-4-21 18:01:05.2|Error|powershell.exe|ze is 25MB.","param":"size","value":"0","max_upload_size":26214400,"cat":"\u003e:3"},"error_code":"invalid_request"}
19-4-21 18:01:05.2|Error|powershell.exe|At C:\Convert\Lidarr.ps1:72 char:1
19-4-21 18:01:05.2|Error|powershell.exe|+ Invoke-RestMethod -Uri $uploadImage.upload_url -Method Post -UseBasic ...
19-4-21 18:01:05.2|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-21 18:01:05.3|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc 
19-4-21 18:01:05.3|Error|powershell.exe|   eption
19-4-21 18:01:05.3|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
19-4-21 18:01:05.3|Error|powershell.exe|rm : Cannot find path 'C:\Convert\coverart.jpg' because it does not exist.
19-4-21 18:01:05.4|Error|powershell.exe|At C:\Convert\Lidarr.ps1:74 char:1
19-4-21 18:01:05.4|Error|powershell.exe|+ rm "$PSScriptRoot\coverart.jpg"
19-4-21 18:01:05.4|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-21 18:01:05.4|Error|powershell.exe|    + CategoryInfo          : ObjectNotFound: (C:\Convert\coverart.jpg:String) [Remove-Item], ItemNotFoundException
19-4-21 18:01:05.5|Error|powershell.exe|    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
19-4-21 18:01:05.7|Error|powershell.exe|Invoke-WebRequest : {"error":{"code":"invalid_param","type":"invalid_request","message":"The param 'file_url' has an in
19-4-21 18:01:05.7|Error|powershell.exe|valid value.","param":"file_url","cat":"\u003e:3"},"error_code":"invalid_param"}
19-4-21 18:01:05.7|Error|powershell.exe|At C:\Convert\Lidarr.ps1:93 char:1
19-4-21 18:01:05.7|Error|powershell.exe|+ Invoke-WebRequest -Method POST -Uri "https://api.pushbullet.com/v2/pu ...
19-4-21 18:01:05.8|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-21 18:01:05.8|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
19-4-21 18:01:05.8|Error|powershell.exe|   eption
19-4-21 18:01:05.9|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

**Comment by CJPCNZ** [comment]
Unfortunately I'm not sure how they're pulling the cover art but I've switched to fanart for now and pushed a new commit. Do you need track notifications as well or just albums?

**Comment by jaycedk** [comment]
Hmmm File C:\ProgramData\Lidarr\MediaCover\fanart.jpg not found
The path is missing the artist id.
I think its located File C:\ProgramData\Lidarr\MediaCover\\[ArtistID]\fanart.jpg

`19-4-22 10:29:51.4|Warn|MediaCoverMapper|File C:\ProgramData\Lidarr\MediaCover\fanart.jpg not found
19-4-22 10:29:51.5|Error|powershell.exe|Invoke-WebRequest : Fjernserveren returnerede en fejl: (404) Ikke fundet.
19-4-22 10:29:51.5|Error|powershell.exe|At C:\Convert\Lidarr.ps1:24 char:1
19-4-22 10:29:51.5|Error|powershell.exe|+ Invoke-WebRequest $lidarr_image -UseBasicParsing -OutFile "$PSScriptR ...
19-4-22 10:29:51.6|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-22 10:29:51.6|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
19-4-22 10:29:51.6|Error|powershell.exe|   eption
19-4-22 10:29:51.7|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
19-4-22 10:30:03.0|Error|powershell.exe|Exception calling "ReadAllBytes" with "1" argument(s): "Filen 'C:\Convert\fanart.jpg' blev ikke fundet."
19-4-22 10:30:03.1|Error|powershell.exe|At C:\Convert\Lidarr.ps1:42 char:1
19-4-22 10:30:03.1|Error|powershell.exe|+ $fileBytes = [System.IO.File]::ReadAllBytes($FilePath);
19-4-22 10:30:03.2|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-22 10:30:03.2|Error|powershell.exe|    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
19-4-22 10:30:03.2|Error|powershell.exe|    + FullyQualifiedErrorId : FileNotFoundException
19-4-22 10:30:03.3|Error|powershell.exe|Exception calling "GetString" with "1" argument(s): "En matrix m† ikke v‘re null.
19-4-22 10:30:03.3|Error|powershell.exe|Parameternavn: bytes"
19-4-22 10:30:03.3|Error|powershell.exe|At C:\Convert\Lidarr.ps1:43 char:1
19-4-22 10:30:03.4|Error|powershell.exe|+ $fileEnc = [System.Text.Encoding]::GetEncoding('ISO-8859-1').GetStrin ...
19-4-22 10:30:03.4|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-22 10:30:03.4|Error|powershell.exe|    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
19-4-22 10:30:03.5|Error|powershell.exe|    + FullyQualifiedErrorId : ArgumentNullException
19-4-22 10:30:03.6|Error|powershell.exe|Invoke-RestMethod : {"error":{"code":"invalid_request","type":"invalid_request","message":"File is too big.  Maximum si
19-4-22 10:30:03.6|Error|powershell.exe|ze is 25MB.","param":"size","value":"0","max_upload_size":26214400,"cat":"\u003e:3"},"error_code":"invalid_request"}
19-4-22 10:30:03.6|Error|powershell.exe|At C:\Convert\Lidarr.ps1:72 char:1
19-4-22 10:30:03.7|Error|powershell.exe|+ Invoke-RestMethod -Uri $uploadImage.upload_url -Method Post -UseBasic ...
19-4-22 10:30:03.7|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-22 10:30:03.8|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc 
19-4-22 10:30:03.8|Error|powershell.exe|   eption
19-4-22 10:30:03.8|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
19-4-22 10:30:03.9|Error|powershell.exe|rm : Cannot find path 'C:\Convert\fanart.jpg' because it does not exist.
19-4-22 10:30:03.9|Error|powershell.exe|At C:\Convert\Lidarr.ps1:74 char:1
19-4-22 10:30:04.0|Error|powershell.exe|+ rm "$PSScriptRoot\fanart.jpg"
19-4-22 10:30:04.0|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-22 10:30:04.1|Error|powershell.exe|    + CategoryInfo          : ObjectNotFound: (C:\Convert\fanart.jpg:String) [Remove-Item], ItemNotFoundException
19-4-22 10:30:04.1|Error|powershell.exe|    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
19-4-22 10:30:04.1|Error|powershell.exe|Invoke-WebRequest : {"error":{"code":"invalid_param","type":"invalid_request","message":"The param 'file_url' has an in
19-4-22 10:30:04.2|Error|powershell.exe|valid value.","param":"file_url","cat":"\u003e:3"},"error_code":"invalid_param"}
19-4-22 10:30:04.2|Error|powershell.exe|At C:\Convert\Lidarr.ps1:93 char:1
19-4-22 10:30:04.3|Error|powershell.exe|+ Invoke-WebRequest -Method POST -Uri "https://api.pushbullet.com/v2/pu ...
19-4-22 10:30:04.3|Error|powershell.exe|+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
19-4-22 10:30:04.4|Error|powershell.exe|    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
19-4-22 10:30:04.4|Error|powershell.exe|   eption
19-4-22 10:30:04.4|Error|powershell.exe|    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

**Comment by CJPCNZ** [comment]
You're correct, I was using Album ID. I've downloaded and installed Lidarr so will do some testing. I've replaced Album ID with Artist ID which should help now.

**Comment by jaycedk** [comment]
Ok getting the picture now :)
