### ISSUE TITLE
Question about radarr events

### ISSUE THREAD

**Issue by sr8087as** [CJPCNZ/CustomPush#5]
Will this script work as is if I just want notifications on "grab" rather than download & upgrade (if I set that option in the radarr custom scripts settings obviously)?

**Comment by CJPCNZ** [comment]
It should work the same however in "On Grab" events Radarr presents "radarr_release_quality" instead of "radarr_moviefile_quality" so you'd have to replace the variable in whichever script you use.

Reference is here: https://github.com/Radarr/Radarr/wiki/Custom-Post-Processing-Scripts

**Comment by sr8087as** [comment]
Thanks for the response! I'll try it out. :)

**Comment by CJPCNZ** [comment]
No worries, let me know how it goes!
